### ISSUE TITLE
ERROR: column "count" does not exist LINE 7: HAVING count > 1

### ISSUE THREAD

**Issue by caiadogithub** [juacas/moodle-report_simultaneous#2]
Moodle 4.1.2+
PostgresSQL 12
PHP 7.4
Ubuntu 20.04

Informações de depuração:  ERROR: column "count" does not exist
LINE 7: HAVING count > 1
^
SELECT DISTINCT userid, COUNT(DISTINCT ip) as count
FROM mdl_logstore_standard_log
WHERE timecreated >= $1
AND timecreated <= $2
AND userid = $3
GROUP BY userid
HAVING count > 1
[array (
0 => 1681266474,
1 => 1681273674,
2 => 2,
)]
Error code: dmlreadexception Rastreamento de pilha: 

    line 494 of /lib/dml/moodle_database.php: dml_read_exception thrown
    line 293 of /lib/dml/moodle_read_slave_trait.php: call to moodle_database->query_end()
    line 341 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->read_slave_query_end()
    line 1027 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
    line 186 of /report/simultaneous/locallib.php: call to pgsql_native_moodle_database->get_records_sql()
    line 378 of /report/simultaneous/locallib.php: call to report_simultaneous_get_users_with_multiple_ips()
    line 207 of /report/simultaneous/index.php: call to report_simultaneous_get_data()

**Comment by juacas** [comment]
It seems that MySQL's SQL has some subtle diferences with Postgres'.
v1.0.8 should be fully compatible with Postgres (tested with Postgres 15.2).
Thank you for reporting.
